### ISSUE TITLE
plantuml/c4plantuml cannot parse sequence diagram delay function as png 

### ISSUE THREAD

**Issue by mduerr3cgi** [yuzutech/plantuml#40]
Hello,
The usage of the delay function in a plantuml/c4plantuml diagram throws the following error if exported as png:

![grafik](https://github.com/yuzutech/kroki/assets/103638698/1f1f8b1a-1a53-4907-81b8-d0c25567df02)

This can be reproduced by using the [offical plantuml delay example](https://plantuml.com/en/sequence-diagram#8f497c1a3d15af9e) in the #try section of kroki.io after changing the format from svg to png in the resulting link.

**Comment by ggrossetie** [comment]
Thanks!
Would you mind adding this example in the GitHub Actions tasks? Similar to what Thomas did to resolve https://github.com/yuzutech/plantuml/pull/38, see: https://github.com/yuzutech/plantuml/commit/b80625cdc337d842e223d578bb00b2317110c0ce

**Comment by Plunts** [comment]
I'm 99% sure that the example by Thomas is the same, as is the error message. I'd guess all we need is a new release of kroki containing the change :)

**Comment by mduerr3cgi** [comment]
I can confirm that the fix by Thomas is working. Hence, this issue is a duplicate and can be closed.
