### ISSUE TITLE
Calendar language for plantuml gantt charts is ignored

### ISSUE THREAD

**Issue by JensReuschling** [yuzutech/plantuml#41]
**The calendar language settings are currently ignored for plantuml gantt charts, so that the calendar labels are always in
English**

**Here is an example where the labels should be in Japanese**
```
@startgantt
language ja
saturday are closed
sunday are closed

Project starts 2024-01-01
[Prototype design end] as [TASK1] requires 19 days
[TASK1] is colored in Lavender/LightBlue
[Testing] requires 14 days
[TASK1]->[Testing]

2024-01-18 to 2024-01-22 are colored in salmon
@endgantt
```

**Expected behavior (as on PlantUML Live Server)**
![image](https://github.com/yuzutech/plantuml/assets/158844714/5c471508-4e8f-4ee6-aff4-7bb96a5d86e8)

**Current behavior (via kroki)**
![image](https://github.com/yuzutech/plantuml/assets/158844714/10a6f776-0787-4b43-8bd9-d0b1ee83681f)

**Additional context**
This is not a new feature, as the possibility to set the calendar language in PlantUML Gantt charts has already existed since 2021.

**Comment by ggrossetie** [comment]
I think we need to add `-H:+IncludeAllLocales` when generating the single binary : https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/Resources/#locales
